### PR TITLE
DM-43714: Use tox-uv for Python templates

### PR DESCRIPTION
**Pull request by rra**
Install the tox-uv plugin to use uv for managing the tox virtual environments, since it's much faster.

For the FastAPI Safir app, move the dependencies for tox and its plugins to a new requirements/tox.in file and a corresponding generated pinnned dependency file, and use the new tox-requirements support in lsst-sqre/run-tox to use the same file in GitHub Actions. Let pre-commit float and manage it only in the Makefile. Stop installing it into tox environments, where it is not needed. Remove ruff from requirements/dev.in; it's only needed by the lint target, where it's handled by pre-commit, and it's not useful inside tox environments.

For SQuaRE PyPI packages, add tox-uv to the Makefile and the GitHub Actions configuration.

### CODE REVIEW

**Comment by rra** [comment]
The thought process behind moving the tox dependency is that it's worthwhile to pin tox and pre-commit to a version that we know we've tested to avoid any problems for someone who is just trying to clone and build. pre-commit was already in the frozen dependencies, so this was just moving tox and removing the separate install lines.

**Review by jonathansick — APPROVED** [review]
I think the reason I didn't initially put tox or pre-commit in the requirements was that, for tox particularly, it seemed wasteful to install tox in tox. On the other hand, this gives us a more consistent organizational approach. So overall, we might as well go with this.

Now, the [run-tox](https://github.com/lsst/run-tox) action also installs tox. run-tox isn't installing from dev.in or through `make init`, so I think that means run-tox usages will get a floating tox compared to whats in a local requirements file. So if we're really after pinning tox in CI so it matches the user's tox then we'll need to modify run-tox (perhaps make a requirements file an input??)

**Comment by rra** [comment]
I've reworked this per our stand-up discussion to instead add a separate tox.in dependency file for the FastAPI Safir app template and use the new run-tox functionality introduced in https://github.com/lsst-sqre/run-tox/pull/10. pre-commit is back in the Makefile, and tox is handled in the Makefile for SQuaRE PyPI libraries.

**Review by jonathansick — APPROVED** [review]
This looks great, thanks!

**Pull request merged**
