### PR TITLE
Remove unnecessary condition E251.

### PR DESCRIPTION
**Pull request by jeffcarlin**

### CODE REVIEW

**Comment by jonathansick** [comment]
Thanks, though we can't merge this just yet. These tests were supposed to fail because they examples weren't updated, but somehow that didn't happen. I'll check on this.

**Comment by jeffcarlin** [comment]
Following step 2 from above, I get permissions errors (see below). I'll just manually edit the files in `templates/project_templates/stack_package`. Is that the only place they need updating?

(lsst-scipipe-10a4fa6) [jcarlin@jld-lab-jcarlin-w201834 templates]$ python setup.py install
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/opt/lsst/software/stack/python/miniconda3-4.5.4/envs/lsst-scipipe-10a4fa6/lib/python3.6/site-packages/test-easy-install-2893.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /opt/lsst/software/stack/python/miniconda3-4.5.4/envs/lsst-scipipe-10a4fa6/lib/python3.6/site-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.readthedocs.io/en/latest/easy_install.html

Please make the appropriate changes for your system and try again.

**Comment by jonathansick** [comment]
Oh, maybe instead of `python setup.py install` you can do `pip install --user -e .` (I think `--user` is the right flag).

JupyterLab has different permission restrictions than normal accounts.

**Comment by jonathansick** [comment]
Sure, I can get this done for you.

Just to check, is it a matter of doing a `git push --force` after a `git rebase`?

**Comment by jeffcarlin** [comment]
May be - shall I try a `git push --force`?

**Comment by jeffcarlin** [comment]
I'm clearly not doing the rebase/push correctly, because `git push --force` tells me there's no upstream branch...

**Comment by jonathansick** [comment]
Merged via #23

**Pull request closed without merging**
